// flow-typed signature: 06860fe22cb82d81b568273bd027e27a
// flow-typed version: <<STUB>>/actions-on-google_v2.0.0-alpha.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'actions-on-google'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'actions-on-google' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'actions-on-google/dist/assistant' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/common' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/framework/express' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/framework/framework' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/framework/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/framework/lambda' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/actionssdk' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/api/v2' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conv' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/argument/argument' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/argument/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/argument/media' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/argument/noinput' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/conversation' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/device' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/input' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/confirmation' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/datetime' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/deeplink' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/newsurface' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/option/carousel' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/option/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/option/list' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/option/option' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/permission/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/permission/permission' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/permission/update' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/place' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/question' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/registerupdate' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/signin' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/transaction/decision' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/transaction/deliveryaddress' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/transaction/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/question/transaction/requirements' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/browse' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/card' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/image' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/linkout' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/media' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/order' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/rich' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/simple' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/suggestion' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/response/url' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/surface' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/conversation/user' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/actionssdk/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/dialogflow/api/v1' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/dialogflow/api/v2' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/dialogflow/context' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/dialogflow/conv' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/dialogflow/dialogflow' {
  declare module.exports: any;
}

declare module 'actions-on-google/dist/service/dialogflow/index' {
  declare module.exports: any;
}

declare module 'actions-on-google/util/ssml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'actions-on-google/dist/assistant.js' {
  declare module.exports: $Exports<'actions-on-google/dist/assistant'>;
}
declare module 'actions-on-google/dist/common.js' {
  declare module.exports: $Exports<'actions-on-google/dist/common'>;
}
declare module 'actions-on-google/dist/framework/express.js' {
  declare module.exports: $Exports<'actions-on-google/dist/framework/express'>;
}
declare module 'actions-on-google/dist/framework/framework.js' {
  declare module.exports: $Exports<'actions-on-google/dist/framework/framework'>;
}
declare module 'actions-on-google/dist/framework/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/framework/index'>;
}
declare module 'actions-on-google/dist/framework/lambda.js' {
  declare module.exports: $Exports<'actions-on-google/dist/framework/lambda'>;
}
declare module 'actions-on-google/dist/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/index'>;
}
declare module 'actions-on-google/dist/service/actionssdk/actionssdk.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/actionssdk'>;
}
declare module 'actions-on-google/dist/service/actionssdk/api/v2.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/api/v2'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conv.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conv'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/argument/argument.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/argument/argument'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/argument/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/argument/index'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/argument/media.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/argument/media'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/argument/noinput.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/argument/noinput'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/conversation.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/conversation'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/device.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/device'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/index'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/input.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/input'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/confirmation.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/confirmation'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/datetime.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/datetime'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/deeplink.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/deeplink'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/index'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/newsurface.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/newsurface'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/option/carousel.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/option/carousel'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/option/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/option/index'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/option/list.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/option/list'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/option/option.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/option/option'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/permission/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/permission/index'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/permission/permission.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/permission/permission'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/permission/update.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/permission/update'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/place.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/place'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/question.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/question'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/registerupdate.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/registerupdate'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/signin.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/signin'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/transaction/decision.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/transaction/decision'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/transaction/deliveryaddress.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/transaction/deliveryaddress'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/transaction/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/transaction/index'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/question/transaction/requirements.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/question/transaction/requirements'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/browse.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/browse'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/card.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/card'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/image.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/image'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/index'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/linkout.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/linkout'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/media.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/media'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/order.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/order'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/rich.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/rich'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/simple.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/simple'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/suggestion.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/suggestion'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/response/url.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/response/url'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/surface.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/surface'>;
}
declare module 'actions-on-google/dist/service/actionssdk/conversation/user.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/conversation/user'>;
}
declare module 'actions-on-google/dist/service/actionssdk/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/actionssdk/index'>;
}
declare module 'actions-on-google/dist/service/dialogflow/api/v1.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/dialogflow/api/v1'>;
}
declare module 'actions-on-google/dist/service/dialogflow/api/v2.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/dialogflow/api/v2'>;
}
declare module 'actions-on-google/dist/service/dialogflow/context.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/dialogflow/context'>;
}
declare module 'actions-on-google/dist/service/dialogflow/conv.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/dialogflow/conv'>;
}
declare module 'actions-on-google/dist/service/dialogflow/dialogflow.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/dialogflow/dialogflow'>;
}
declare module 'actions-on-google/dist/service/dialogflow/index.js' {
  declare module.exports: $Exports<'actions-on-google/dist/service/dialogflow/index'>;
}
declare module 'actions-on-google/util/ssml.js' {
  declare module.exports: $Exports<'actions-on-google/util/ssml'>;
}
