// flow-typed signature: 7e914019864c476f1c532856c9aed43e
// flow-typed version: <<STUB>>/dialogflow-fulfillment_v^0.3.0-beta.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dialogflow-fulfillment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dialogflow-fulfillment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dialogflow-fulfillment/src/dialogflow-fulfillment' {
  declare module.exports: any;
}

declare module 'dialogflow-fulfillment/src/rich-responses/card-response' {
  declare module.exports: any;
}

declare module 'dialogflow-fulfillment/src/rich-responses/image-response' {
  declare module.exports: any;
}

declare module 'dialogflow-fulfillment/src/rich-responses/payload-response' {
  declare module.exports: any;
}

declare module 'dialogflow-fulfillment/src/rich-responses/rich-response' {
  declare module.exports: any;
}

declare module 'dialogflow-fulfillment/src/rich-responses/suggestions-response' {
  declare module.exports: any;
}

declare module 'dialogflow-fulfillment/src/rich-responses/text-response' {
  declare module.exports: any;
}

declare module 'dialogflow-fulfillment/src/v1-agent' {
  declare module.exports: any;
}

declare module 'dialogflow-fulfillment/src/v2-agent' {
  declare class agentType {
    add(): void;
  }
}

// Filename aliases
declare module 'dialogflow-fulfillment/src/dialogflow-fulfillment.js' {
  declare module.exports: $Exports<'dialogflow-fulfillment/src/dialogflow-fulfillment'>;
}
declare module 'dialogflow-fulfillment/src/rich-responses/card-response.js' {
  declare module.exports: $Exports<'dialogflow-fulfillment/src/rich-responses/card-response'>;
}
declare module 'dialogflow-fulfillment/src/rich-responses/image-response.js' {
  declare module.exports: $Exports<'dialogflow-fulfillment/src/rich-responses/image-response'>;
}
declare module 'dialogflow-fulfillment/src/rich-responses/payload-response.js' {
  declare module.exports: $Exports<'dialogflow-fulfillment/src/rich-responses/payload-response'>;
}
declare module 'dialogflow-fulfillment/src/rich-responses/rich-response.js' {
  declare module.exports: $Exports<'dialogflow-fulfillment/src/rich-responses/rich-response'>;
}
declare module 'dialogflow-fulfillment/src/rich-responses/suggestions-response.js' {
  declare module.exports: $Exports<
    'dialogflow-fulfillment/src/rich-responses/suggestions-response',
  >;
}
declare module 'dialogflow-fulfillment/src/rich-responses/text-response.js' {
  declare module.exports: $Exports<'dialogflow-fulfillment/src/rich-responses/text-response'>;
}
declare module 'dialogflow-fulfillment/src/v1-agent.js' {
  declare module.exports: $Exports<'dialogflow-fulfillment/src/v1-agent'>;
}
declare module 'dialogflow-fulfillment/src/v2-agent.js' {
  declare module.exports: $Exports<'dialogflow-fulfillment/src/v2-agent'>;
}
