// flow-typed signature: 3b460030b8470c9cf0fa2540f61eb7ee
// flow-typed version: <<STUB>>/http_v0.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http' {
  declare module.exports: any;
}
