exports.response = {
  data: {
    request: [
      {
        type: 'City',
        query: 'London, United Kingdom',
      },
    ],
    current_condition: [
      {
        observation_time: '07:31 PM',
        temp_C: '26',
        temp_F: '79',
        weatherCode: '113',
        weatherIconUrl: [
          {
            value:
              'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
          },
        ],
        weatherDesc: [
          {
            value: 'Sunny',
          },
        ],
        windspeedMiles: '9',
        windspeedKmph: '15',
        winddirDegree: '200',
        winddir16Point: 'SSW',
        precipMM: '0.0',
        humidity: '54',
        visibility: '10',
        pressure: '1016',
        cloudcover: '0',
        FeelsLikeC: '27',
        FeelsLikeF: '80',
      },
    ],
    weather: [
      {
        date: '2018-07-05',
        astronomy: [
          {
            sunrise: '04:50 AM',
            sunset: '09:19 PM',
            moonrise: '12:30 AM',
            moonset: '12:11 PM',
            moon_phase: 'Last Quarter',
            moon_illumination: '55',
          },
        ],
        maxtempC: '29',
        maxtempF: '83',
        mintempC: '19',
        mintempF: '66',
        totalSnow_cm: '0.0',
        sunHour: '16.6',
        uvIndex: '7',
        hourly: [
          {
            time: '0',
            tempC: '21',
            tempF: '69',
            windspeedMiles: '4',
            windspeedKmph: '7',
            winddirDegree: '225',
            winddir16Point: 'SW',
            weatherCode: '176',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Patchy rain possible',
              },
            ],
            precipMM: '0.4',
            humidity: '77',
            visibility: '9',
            pressure: '1015',
            cloudcover: '70',
            HeatIndexC: '21',
            HeatIndexF: '69',
            DewPointC: '16',
            DewPointF: '61',
            WindChillC: '21',
            WindChillF: '69',
            WindGustMiles: '5',
            WindGustKmph: '8',
            FeelsLikeC: '21',
            FeelsLikeF: '69',
            chanceofrain: '98',
            chanceofremdry: '0',
            chanceofwindy: '0',
            chanceofovercast: '92',
            chanceofsunshine: '0',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '300',
            tempC: '19',
            tempF: '66',
            windspeedMiles: '5',
            windspeedKmph: '8',
            winddirDegree: '241',
            winddir16Point: 'WSW',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '80',
            visibility: '20',
            pressure: '1015',
            cloudcover: '24',
            HeatIndexC: '19',
            HeatIndexF: '66',
            DewPointC: '15',
            DewPointF: '59',
            WindChillC: '19',
            WindChillF: '66',
            WindGustMiles: '6',
            WindGustKmph: '9',
            FeelsLikeC: '19',
            FeelsLikeF: '66',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '48',
            chanceofsunshine: '70',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '600',
            tempC: '19',
            tempF: '66',
            windspeedMiles: '4',
            windspeedKmph: '7',
            winddirDegree: '263',
            winddir16Point: 'W',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '75',
            visibility: '20',
            pressure: '1015',
            cloudcover: '17',
            HeatIndexC: '19',
            HeatIndexF: '66',
            DewPointC: '15',
            DewPointF: '58',
            WindChillC: '19',
            WindChillF: '66',
            WindGustMiles: '5',
            WindGustKmph: '8',
            FeelsLikeC: '19',
            FeelsLikeF: '66',
            chanceofrain: '0',
            chanceofremdry: '90',
            chanceofwindy: '0',
            chanceofovercast: '37',
            chanceofsunshine: '74',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '900',
            tempC: '25',
            tempF: '77',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '344',
            winddir16Point: 'NNW',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '47',
            visibility: '17',
            pressure: '1016',
            cloudcover: '22',
            HeatIndexC: '26',
            HeatIndexF: '78',
            DewPointC: '13',
            DewPointF: '55',
            WindChillC: '25',
            WindChillF: '77',
            WindGustMiles: '5',
            WindGustKmph: '8',
            FeelsLikeC: '26',
            FeelsLikeF: '78',
            chanceofrain: '0',
            chanceofremdry: '88',
            chanceofwindy: '0',
            chanceofovercast: '30',
            chanceofsunshine: '73',
            chanceoffrost: '0',
            chanceofhightemp: '15',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1200',
            tempC: '29',
            tempF: '83',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '6',
            winddir16Point: 'N',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '34',
            visibility: '17',
            pressure: '1016',
            cloudcover: '80',
            HeatIndexC: '28',
            HeatIndexF: '82',
            DewPointC: '11',
            DewPointF: '52',
            WindChillC: '29',
            WindChillF: '83',
            WindGustMiles: '5',
            WindGustKmph: '8',
            FeelsLikeC: '28',
            FeelsLikeF: '82',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '89',
            chanceofsunshine: '18',
            chanceoffrost: '0',
            chanceofhightemp: '98',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1500',
            tempC: '27',
            tempF: '80',
            windspeedMiles: '6',
            windspeedKmph: '9',
            winddirDegree: '340',
            winddir16Point: 'NNW',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '38',
            visibility: '17',
            pressure: '1016',
            cloudcover: '60',
            HeatIndexC: '27',
            HeatIndexF: '80',
            DewPointC: '11',
            DewPointF: '53',
            WindChillC: '27',
            WindChillF: '80',
            WindGustMiles: '6',
            WindGustKmph: '10',
            FeelsLikeC: '27',
            FeelsLikeF: '80',
            chanceofrain: '0',
            chanceofremdry: '80',
            chanceofwindy: '0',
            chanceofovercast: '30',
            chanceofsunshine: '78',
            chanceoffrost: '0',
            chanceofhightemp: '97',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1800',
            tempC: '25',
            tempF: '77',
            windspeedMiles: '7',
            windspeedKmph: '12',
            winddirDegree: '334',
            winddir16Point: 'NNW',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '32',
            visibility: '17',
            pressure: '1016',
            cloudcover: '8',
            HeatIndexC: '27',
            HeatIndexF: '80',
            DewPointC: '10',
            DewPointF: '49',
            WindChillC: '25',
            WindChillF: '77',
            WindGustMiles: '8',
            WindGustKmph: '13',
            FeelsLikeC: '27',
            FeelsLikeF: '80',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '34',
            chanceofsunshine: '74',
            chanceoffrost: '0',
            chanceofhightemp: '96',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '2100',
            tempC: '19',
            tempF: '66',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '2',
            winddir16Point: 'N',
            weatherCode: '113',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Sunny',
              },
            ],
            precipMM: '0.0',
            humidity: '41',
            visibility: '18',
            pressure: '1018',
            cloudcover: '0',
            HeatIndexC: '22',
            HeatIndexF: '71',
            DewPointC: '12',
            DewPointF: '54',
            WindChillC: '19',
            WindChillF: '66',
            WindGustMiles: '8',
            WindGustKmph: '13',
            FeelsLikeC: '19',
            FeelsLikeF: '66',
            chanceofrain: '0',
            chanceofremdry: '88',
            chanceofwindy: '0',
            chanceofovercast: '0',
            chanceofsunshine: '93',
            chanceoffrost: '0',
            chanceofhightemp: '95',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
        ],
      },
      {
        date: '2018-07-06',
        astronomy: [
          {
            sunrise: '04:51 AM',
            sunset: '09:19 PM',
            moonrise: '12:52 AM',
            moonset: '01:21 PM',
            moon_phase: 'Waning Crescent',
            moon_illumination: '48',
          },
        ],
        maxtempC: '29',
        maxtempF: '84',
        mintempC: '21',
        mintempF: '70',
        totalSnow_cm: '0.0',
        sunHour: '16.7',
        uvIndex: '8',
        hourly: [
          {
            time: '0',
            tempC: '23',
            tempF: '73',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '24',
            winddir16Point: 'NNE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '57',
            visibility: '18',
            pressure: '1019',
            cloudcover: '8',
            HeatIndexC: '25',
            HeatIndexF: '77',
            DewPointC: '14',
            DewPointF: '57',
            WindChillC: '23',
            WindChillF: '73',
            WindGustMiles: '4',
            WindGustKmph: '6',
            FeelsLikeC: '25',
            FeelsLikeF: '77',
            chanceofrain: '0',
            chanceofremdry: '91',
            chanceofwindy: '0',
            chanceofovercast: '43',
            chanceofsunshine: '79',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '300',
            tempC: '20',
            tempF: '69',
            windspeedMiles: '3',
            windspeedKmph: '5',
            winddirDegree: '14',
            winddir16Point: 'NNE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '67',
            visibility: '20',
            pressure: '1019',
            cloudcover: '24',
            HeatIndexC: '20',
            HeatIndexF: '69',
            DewPointC: '14',
            DewPointF: '57',
            WindChillC: '20',
            WindChillF: '69',
            WindGustMiles: '4',
            WindGustKmph: '7',
            FeelsLikeC: '20',
            FeelsLikeF: '69',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '48',
            chanceofsunshine: '70',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '600',
            tempC: '20',
            tempF: '69',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '11',
            winddir16Point: 'NNE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '66',
            visibility: '20',
            pressure: '1020',
            cloudcover: '31',
            HeatIndexC: '20',
            HeatIndexF: '69',
            DewPointC: '14',
            DewPointF: '57',
            WindChillC: '20',
            WindChillF: '69',
            WindGustMiles: '5',
            WindGustKmph: '8',
            FeelsLikeC: '20',
            FeelsLikeF: '69',
            chanceofrain: '0',
            chanceofremdry: '91',
            chanceofwindy: '0',
            chanceofovercast: '45',
            chanceofsunshine: '75',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '900',
            tempC: '26',
            tempF: '79',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '6',
            winddir16Point: 'N',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '48',
            visibility: '20',
            pressure: '1021',
            cloudcover: '4',
            HeatIndexC: '27',
            HeatIndexF: '80',
            DewPointC: '14',
            DewPointF: '57',
            WindChillC: '26',
            WindChillF: '79',
            WindGustMiles: '4',
            WindGustKmph: '6',
            FeelsLikeC: '27',
            FeelsLikeF: '80',
            chanceofrain: '0',
            chanceofremdry: '81',
            chanceofwindy: '0',
            chanceofovercast: '34',
            chanceofsunshine: '70',
            chanceoffrost: '0',
            chanceofhightemp: '80',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1200',
            tempC: '29',
            tempF: '84',
            windspeedMiles: '3',
            windspeedKmph: '5',
            winddirDegree: '318',
            winddir16Point: 'NW',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '36',
            visibility: '20',
            pressure: '1022',
            cloudcover: '35',
            HeatIndexC: '29',
            HeatIndexF: '83',
            DewPointC: '13',
            DewPointF: '55',
            WindChillC: '29',
            WindChillF: '84',
            WindGustMiles: '4',
            WindGustKmph: '6',
            FeelsLikeC: '29',
            FeelsLikeF: '83',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '44',
            chanceofsunshine: '81',
            chanceoffrost: '0',
            chanceofhightemp: '94',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1500',
            tempC: '29',
            tempF: '84',
            windspeedMiles: '5',
            windspeedKmph: '8',
            winddirDegree: '315',
            winddir16Point: 'NW',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '35',
            visibility: '18',
            pressure: '1022',
            cloudcover: '51',
            HeatIndexC: '28',
            HeatIndexF: '83',
            DewPointC: '12',
            DewPointF: '53',
            WindChillC: '29',
            WindChillF: '84',
            WindGustMiles: '6',
            WindGustKmph: '9',
            FeelsLikeC: '28',
            FeelsLikeF: '83',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '30',
            chanceofsunshine: '78',
            chanceoffrost: '0',
            chanceofhightemp: '92',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1800',
            tempC: '28',
            tempF: '82',
            windspeedMiles: '8',
            windspeedKmph: '12',
            winddirDegree: '332',
            winddir16Point: 'NNW',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '38',
            visibility: '19',
            pressure: '1022',
            cloudcover: '28',
            HeatIndexC: '27',
            HeatIndexF: '81',
            DewPointC: '12',
            DewPointF: '54',
            WindChillC: '28',
            WindChillF: '82',
            WindGustMiles: '9',
            WindGustKmph: '14',
            FeelsLikeC: '27',
            FeelsLikeF: '81',
            chanceofrain: '0',
            chanceofremdry: '82',
            chanceofwindy: '0',
            chanceofovercast: '49',
            chanceofsunshine: '83',
            chanceoffrost: '0',
            chanceofhightemp: '89',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '2100',
            tempC: '25',
            tempF: '78',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '345',
            winddir16Point: 'NNW',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '47',
            visibility: '20',
            pressure: '1023',
            cloudcover: '5',
            HeatIndexC: '26',
            HeatIndexF: '79',
            DewPointC: '13',
            DewPointF: '56',
            WindChillC: '25',
            WindChillF: '78',
            WindGustMiles: '8',
            WindGustKmph: '13',
            FeelsLikeC: '26',
            FeelsLikeF: '79',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '30',
            chanceofsunshine: '88',
            chanceoffrost: '0',
            chanceofhightemp: '68',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
        ],
      },
      {
        date: '2018-07-07',
        astronomy: [
          {
            sunrise: '04:52 AM',
            sunset: '09:18 PM',
            moonrise: '01:14 AM',
            moonset: '02:32 PM',
            moon_phase: 'Waning Crescent',
            moon_illumination: '41',
          },
        ],
        maxtempC: '31',
        maxtempF: '87',
        mintempC: '21',
        mintempF: '69',
        totalSnow_cm: '0.0',
        sunHour: '14.9',
        uvIndex: '8',
        hourly: [
          {
            time: '0',
            tempC: '23',
            tempF: '74',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '27',
            winddir16Point: 'NNE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '59',
            visibility: '20',
            pressure: '1024',
            cloudcover: '9',
            HeatIndexC: '25',
            HeatIndexF: '77',
            DewPointC: '15',
            DewPointF: '59',
            WindChillC: '23',
            WindChillF: '74',
            WindGustMiles: '4',
            WindGustKmph: '6',
            FeelsLikeC: '25',
            FeelsLikeF: '77',
            chanceofrain: '0',
            chanceofremdry: '94',
            chanceofwindy: '0',
            chanceofovercast: '33',
            chanceofsunshine: '70',
            chanceoffrost: '0',
            chanceofhightemp: '10',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '300',
            tempC: '21',
            tempF: '70',
            windspeedMiles: '2',
            windspeedKmph: '3',
            winddirDegree: '53',
            winddir16Point: 'NE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '68',
            visibility: '20',
            pressure: '1024',
            cloudcover: '19',
            HeatIndexC: '24',
            HeatIndexF: '76',
            DewPointC: '15',
            DewPointF: '59',
            WindChillC: '21',
            WindChillF: '70',
            WindGustMiles: '2',
            WindGustKmph: '4',
            FeelsLikeC: '21',
            FeelsLikeF: '70',
            chanceofrain: '0',
            chanceofremdry: '86',
            chanceofwindy: '0',
            chanceofovercast: '30',
            chanceofsunshine: '75',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '600',
            tempC: '22',
            tempF: '72',
            windspeedMiles: '2',
            windspeedKmph: '3',
            winddirDegree: '74',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '65',
            visibility: '20',
            pressure: '1024',
            cloudcover: '14',
            HeatIndexC: '25',
            HeatIndexF: '76',
            DewPointC: '15',
            DewPointF: '60',
            WindChillC: '22',
            WindChillF: '72',
            WindGustMiles: '2',
            WindGustKmph: '3',
            FeelsLikeC: '25',
            FeelsLikeF: '76',
            chanceofrain: '0',
            chanceofremdry: '81',
            chanceofwindy: '0',
            chanceofovercast: '40',
            chanceofsunshine: '72',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '900',
            tempC: '27',
            tempF: '80',
            windspeedMiles: '2',
            windspeedKmph: '4',
            winddirDegree: '43',
            winddir16Point: 'NE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '47',
            visibility: '20',
            pressure: '1025',
            cloudcover: '11',
            HeatIndexC: '27',
            HeatIndexF: '81',
            DewPointC: '15',
            DewPointF: '58',
            WindChillC: '27',
            WindChillF: '80',
            WindGustMiles: '3',
            WindGustKmph: '5',
            FeelsLikeC: '27',
            FeelsLikeF: '81',
            chanceofrain: '0',
            chanceofremdry: '94',
            chanceofwindy: '0',
            chanceofovercast: '31',
            chanceofsunshine: '83',
            chanceoffrost: '0',
            chanceofhightemp: '82',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1200',
            tempC: '31',
            tempF: '87',
            windspeedMiles: '2',
            windspeedKmph: '4',
            winddirDegree: '31',
            winddir16Point: 'NNE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '34',
            visibility: '18',
            pressure: '1025',
            cloudcover: '45',
            HeatIndexC: '30',
            HeatIndexF: '86',
            DewPointC: '13',
            DewPointF: '55',
            WindChillC: '31',
            WindChillF: '87',
            WindGustMiles: '2',
            WindGustKmph: '4',
            FeelsLikeC: '30',
            FeelsLikeF: '86',
            chanceofrain: '0',
            chanceofremdry: '86',
            chanceofwindy: '0',
            chanceofovercast: '43',
            chanceofsunshine: '85',
            chanceoffrost: '0',
            chanceofhightemp: '90',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1500',
            tempC: '28',
            tempF: '82',
            windspeedMiles: '2',
            windspeedKmph: '4',
            winddirDegree: '47',
            winddir16Point: 'NE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '41',
            visibility: '15',
            pressure: '1024',
            cloudcover: '68',
            HeatIndexC: '28',
            HeatIndexF: '82',
            DewPointC: '14',
            DewPointF: '56',
            WindChillC: '28',
            WindChillF: '82',
            WindGustMiles: '2',
            WindGustKmph: '4',
            FeelsLikeC: '28',
            FeelsLikeF: '82',
            chanceofrain: '0',
            chanceofremdry: '84',
            chanceofwindy: '0',
            chanceofovercast: '87',
            chanceofsunshine: '17',
            chanceoffrost: '0',
            chanceofhightemp: '85',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1800',
            tempC: '27',
            tempF: '80',
            windspeedMiles: '4',
            windspeedKmph: '7',
            winddirDegree: '82',
            winddir16Point: 'E',
            weatherCode: '176',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Patchy rain possible',
              },
            ],
            precipMM: '0.1',
            humidity: '49',
            visibility: '15',
            pressure: '1024',
            cloudcover: '65',
            HeatIndexC: '27',
            HeatIndexF: '81',
            DewPointC: '15',
            DewPointF: '59',
            WindChillC: '27',
            WindChillF: '80',
            WindGustMiles: '5',
            WindGustKmph: '8',
            FeelsLikeC: '27',
            FeelsLikeF: '81',
            chanceofrain: '79',
            chanceofremdry: '0',
            chanceofwindy: '0',
            chanceofovercast: '90',
            chanceofsunshine: '0',
            chanceoffrost: '0',
            chanceofhightemp: '80',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '2100',
            tempC: '24',
            tempF: '75',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '120',
            winddir16Point: 'ESE',
            weatherCode: '176',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Patchy rain possible',
              },
            ],
            precipMM: '0.3',
            humidity: '62',
            visibility: '19',
            pressure: '1026',
            cloudcover: '82',
            HeatIndexC: '25',
            HeatIndexF: '78',
            DewPointC: '16',
            DewPointF: '61',
            WindChillC: '24',
            WindChillF: '75',
            WindGustMiles: '9',
            WindGustKmph: '14',
            FeelsLikeC: '25',
            FeelsLikeF: '78',
            chanceofrain: '69',
            chanceofremdry: '0',
            chanceofwindy: '0',
            chanceofovercast: '81',
            chanceofsunshine: '0',
            chanceoffrost: '0',
            chanceofhightemp: '10',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
        ],
      },
      {
        date: '2018-07-08',
        astronomy: [
          {
            sunrise: '04:53 AM',
            sunset: '09:18 PM',
            moonrise: '01:37 AM',
            moonset: '03:47 PM',
            moon_phase: 'Waning Crescent',
            moon_illumination: '34',
          },
        ],
        maxtempC: '29',
        maxtempF: '83',
        mintempC: '22',
        mintempF: '71',
        totalSnow_cm: '0.0',
        sunHour: '16.7',
        uvIndex: '8',
        hourly: [
          {
            time: '0',
            tempC: '22',
            tempF: '71',
            windspeedMiles: '5',
            windspeedKmph: '8',
            winddirDegree: '136',
            winddir16Point: 'SE',
            weatherCode: '353',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Light rain shower',
              },
            ],
            precipMM: '0.2',
            humidity: '64',
            visibility: '20',
            pressure: '1026',
            cloudcover: '57',
            HeatIndexC: '25',
            HeatIndexF: '76',
            DewPointC: '15',
            DewPointF: '58',
            WindChillC: '22',
            WindChillF: '71',
            WindGustMiles: '6',
            WindGustKmph: '10',
            FeelsLikeC: '22',
            FeelsLikeF: '71',
            chanceofrain: '67',
            chanceofremdry: '0',
            chanceofwindy: '0',
            chanceofovercast: '88',
            chanceofsunshine: '0',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '300',
            tempC: '21',
            tempF: '69',
            windspeedMiles: '3',
            windspeedKmph: '4',
            winddirDegree: '133',
            winddir16Point: 'SE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '63',
            visibility: '20',
            pressure: '1027',
            cloudcover: '44',
            HeatIndexC: '21',
            HeatIndexF: '69',
            DewPointC: '13',
            DewPointF: '56',
            WindChillC: '21',
            WindChillF: '69',
            WindGustMiles: '3',
            WindGustKmph: '5',
            FeelsLikeC: '21',
            FeelsLikeF: '69',
            chanceofrain: '0',
            chanceofremdry: '88',
            chanceofwindy: '0',
            chanceofovercast: '35',
            chanceofsunshine: '78',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '600',
            tempC: '22',
            tempF: '71',
            windspeedMiles: '2',
            windspeedKmph: '4',
            winddirDegree: '113',
            winddir16Point: 'ESE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '57',
            visibility: '20',
            pressure: '1027',
            cloudcover: '11',
            HeatIndexC: '25',
            HeatIndexF: '76',
            DewPointC: '13',
            DewPointF: '55',
            WindChillC: '22',
            WindChillF: '71',
            WindGustMiles: '3',
            WindGustKmph: '5',
            FeelsLikeC: '22',
            FeelsLikeF: '71',
            chanceofrain: '0',
            chanceofremdry: '80',
            chanceofwindy: '0',
            chanceofovercast: '36',
            chanceofsunshine: '85',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '900',
            tempC: '26',
            tempF: '79',
            windspeedMiles: '3',
            windspeedKmph: '5',
            winddirDegree: '67',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '47',
            visibility: '20',
            pressure: '1028',
            cloudcover: '8',
            HeatIndexC: '27',
            HeatIndexF: '80',
            DewPointC: '14',
            DewPointF: '57',
            WindChillC: '26',
            WindChillF: '79',
            WindGustMiles: '4',
            WindGustKmph: '6',
            FeelsLikeC: '27',
            FeelsLikeF: '80',
            chanceofrain: '0',
            chanceofremdry: '81',
            chanceofwindy: '0',
            chanceofovercast: '41',
            chanceofsunshine: '74',
            chanceoffrost: '0',
            chanceofhightemp: '72',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1200',
            tempC: '29',
            tempF: '83',
            windspeedMiles: '5',
            windspeedKmph: '9',
            winddirDegree: '59',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '36',
            visibility: '20',
            pressure: '1027',
            cloudcover: '40',
            HeatIndexC: '28',
            HeatIndexF: '82',
            DewPointC: '12',
            DewPointF: '54',
            WindChillC: '29',
            WindChillF: '83',
            WindGustMiles: '6',
            WindGustKmph: '10',
            FeelsLikeC: '28',
            FeelsLikeF: '82',
            chanceofrain: '0',
            chanceofremdry: '92',
            chanceofwindy: '0',
            chanceofovercast: '43',
            chanceofsunshine: '80',
            chanceoffrost: '0',
            chanceofhightemp: '84',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1500',
            tempC: '29',
            tempF: '83',
            windspeedMiles: '5',
            windspeedKmph: '8',
            winddirDegree: '43',
            winddir16Point: 'NE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '37',
            visibility: '20',
            pressure: '1027',
            cloudcover: '41',
            HeatIndexC: '28',
            HeatIndexF: '83',
            DewPointC: '13',
            DewPointF: '55',
            WindChillC: '29',
            WindChillF: '83',
            WindGustMiles: '6',
            WindGustKmph: '9',
            FeelsLikeC: '28',
            FeelsLikeF: '83',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '44',
            chanceofsunshine: '70',
            chanceoffrost: '0',
            chanceofhightemp: '83',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1800',
            tempC: '27',
            tempF: '81',
            windspeedMiles: '3',
            windspeedKmph: '5',
            winddirDegree: '72',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '43',
            visibility: '20',
            pressure: '1027',
            cloudcover: '56',
            HeatIndexC: '27',
            HeatIndexF: '81',
            DewPointC: '14',
            DewPointF: '56',
            WindChillC: '27',
            WindChillF: '81',
            WindGustMiles: '4',
            WindGustKmph: '6',
            FeelsLikeC: '27',
            FeelsLikeF: '81',
            chanceofrain: '0',
            chanceofremdry: '84',
            chanceofwindy: '0',
            chanceofovercast: '44',
            chanceofsunshine: '70',
            chanceoffrost: '0',
            chanceofhightemp: '80',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '2100',
            tempC: '24',
            tempF: '75',
            windspeedMiles: '6',
            windspeedKmph: '9',
            winddirDegree: '155',
            winddir16Point: 'SSE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '55',
            visibility: '20',
            pressure: '1028',
            cloudcover: '40',
            HeatIndexC: '25',
            HeatIndexF: '78',
            DewPointC: '14',
            DewPointF: '58',
            WindChillC: '24',
            WindChillF: '75',
            WindGustMiles: '7',
            WindGustKmph: '12',
            FeelsLikeC: '25',
            FeelsLikeF: '78',
            chanceofrain: '0',
            chanceofremdry: '80',
            chanceofwindy: '0',
            chanceofovercast: '44',
            chanceofsunshine: '88',
            chanceoffrost: '0',
            chanceofhightemp: '10',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
        ],
      },
      {
        date: '2018-07-09',
        astronomy: [
          {
            sunrise: '04:54 AM',
            sunset: '09:17 PM',
            moonrise: '02:04 AM',
            moonset: '05:03 PM',
            moon_phase: 'Waning Crescent',
            moon_illumination: '28',
          },
        ],
        maxtempC: '29',
        maxtempF: '83',
        mintempC: '18',
        mintempF: '65',
        totalSnow_cm: '0.0',
        sunHour: '13.3',
        uvIndex: '8',
        hourly: [
          {
            time: '0',
            tempC: '23',
            tempF: '74',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '169',
            winddir16Point: 'S',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '62',
            visibility: '20',
            pressure: '1028',
            cloudcover: '6',
            HeatIndexC: '25',
            HeatIndexF: '77',
            DewPointC: '15',
            DewPointF: '60',
            WindChillC: '23',
            WindChillF: '74',
            WindGustMiles: '4',
            WindGustKmph: '7',
            FeelsLikeC: '25',
            FeelsLikeF: '77',
            chanceofrain: '0',
            chanceofremdry: '86',
            chanceofwindy: '0',
            chanceofovercast: '43',
            chanceofsunshine: '88',
            chanceoffrost: '0',
            chanceofhightemp: '10',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '300',
            tempC: '22',
            tempF: '72',
            windspeedMiles: '2',
            windspeedKmph: '3',
            winddirDegree: '178',
            winddir16Point: 'S',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '66',
            visibility: '20',
            pressure: '1028',
            cloudcover: '5',
            HeatIndexC: '25',
            HeatIndexF: '76',
            DewPointC: '16',
            DewPointF: '60',
            WindChillC: '22',
            WindChillF: '72',
            WindGustMiles: '2',
            WindGustKmph: '3',
            FeelsLikeC: '25',
            FeelsLikeF: '76',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '37',
            chanceofsunshine: '82',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '600',
            tempC: '22',
            tempF: '71',
            windspeedMiles: '1',
            windspeedKmph: '2',
            winddirDegree: '23',
            winddir16Point: 'NNE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '63',
            visibility: '20',
            pressure: '1028',
            cloudcover: '67',
            HeatIndexC: '25',
            HeatIndexF: '76',
            DewPointC: '14',
            DewPointF: '58',
            WindChillC: '22',
            WindChillF: '71',
            WindGustMiles: '2',
            WindGustKmph: '3',
            FeelsLikeC: '22',
            FeelsLikeF: '71',
            chanceofrain: '0',
            chanceofremdry: '92',
            chanceofwindy: '0',
            chanceofovercast: '87',
            chanceofsunshine: '17',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '900',
            tempC: '26',
            tempF: '79',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '48',
            winddir16Point: 'NE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '46',
            visibility: '20',
            pressure: '1028',
            cloudcover: '13',
            HeatIndexC: '27',
            HeatIndexF: '80',
            DewPointC: '14',
            DewPointF: '57',
            WindChillC: '26',
            WindChillF: '79',
            WindGustMiles: '4',
            WindGustKmph: '6',
            FeelsLikeC: '27',
            FeelsLikeF: '80',
            chanceofrain: '0',
            chanceofremdry: '82',
            chanceofwindy: '0',
            chanceofovercast: '48',
            chanceofsunshine: '75',
            chanceoffrost: '0',
            chanceofhightemp: '72',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1200',
            tempC: '29',
            tempF: '83',
            windspeedMiles: '5',
            windspeedKmph: '8',
            winddirDegree: '16',
            winddir16Point: 'NNE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            precipMM: '0.0',
            humidity: '39',
            visibility: '20',
            pressure: '1028',
            cloudcover: '88',
            HeatIndexC: '28',
            HeatIndexF: '83',
            DewPointC: '13',
            DewPointF: '56',
            WindChillC: '29',
            WindChillF: '83',
            WindGustMiles: '6',
            WindGustKmph: '9',
            FeelsLikeC: '28',
            FeelsLikeF: '83',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '88',
            chanceofsunshine: '16',
            chanceoffrost: '0',
            chanceofhightemp: '80',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1500',
            tempC: '27',
            tempF: '81',
            windspeedMiles: '5',
            windspeedKmph: '8',
            winddirDegree: '29',
            winddir16Point: 'NNE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            precipMM: '0.0',
            humidity: '43',
            visibility: '19',
            pressure: '1027',
            cloudcover: '78',
            HeatIndexC: '27',
            HeatIndexF: '81',
            DewPointC: '14',
            DewPointF: '56',
            WindChillC: '27',
            WindChillF: '81',
            WindGustMiles: '6',
            WindGustKmph: '9',
            FeelsLikeC: '27',
            FeelsLikeF: '81',
            chanceofrain: '0',
            chanceofremdry: '80',
            chanceofwindy: '0',
            chanceofovercast: '94',
            chanceofsunshine: '19',
            chanceoffrost: '0',
            chanceofhightemp: '77',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '1800',
            tempC: '27',
            tempF: '80',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '78',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            precipMM: '0.0',
            humidity: '47',
            visibility: '18',
            pressure: '1027',
            cloudcover: '90',
            HeatIndexC: '27',
            HeatIndexF: '81',
            DewPointC: '15',
            DewPointF: '58',
            WindChillC: '27',
            WindChillF: '80',
            WindGustMiles: '5',
            WindGustKmph: '8',
            FeelsLikeC: '27',
            FeelsLikeF: '81',
            chanceofrain: '0',
            chanceofremdry: '84',
            chanceofwindy: '0',
            chanceofovercast: '86',
            chanceofsunshine: '13',
            chanceoffrost: '0',
            chanceofhightemp: '71',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
          {
            time: '2100',
            tempC: '23',
            tempF: '74',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '110',
            winddir16Point: 'ESE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            precipMM: '0.0',
            humidity: '60',
            visibility: '20',
            pressure: '1028',
            cloudcover: '100',
            HeatIndexC: '25',
            HeatIndexF: '77',
            DewPointC: '15',
            DewPointF: '59',
            WindChillC: '23',
            WindChillF: '74',
            WindGustMiles: '8',
            WindGustKmph: '13',
            FeelsLikeC: '25',
            FeelsLikeF: '77',
            chanceofrain: '0',
            chanceofremdry: '90',
            chanceofwindy: '0',
            chanceofovercast: '83',
            chanceofsunshine: '5',
            chanceoffrost: '0',
            chanceofhightemp: '11',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
          },
        ],
      },
    ],
    ClimateAverages: [
      {
        month: [
          {
            index: '1',
            name: 'January',
            avgMinTemp: '2.4',
            avgMinTemp_F: '36.3',
            absMaxTemp: '8.6',
            absMaxTemp_F: '47.5',
            avgDailyRainfall: '2.44',
          },
          {
            index: '2',
            name: 'February',
            avgMinTemp: '2.4',
            avgMinTemp_F: '36.3',
            absMaxTemp: '9.7',
            absMaxTemp_F: '49.5',
            avgDailyRainfall: '2.32',
          },
          {
            index: '3',
            name: 'March',
            avgMinTemp: '3.7',
            avgMinTemp_F: '38.7',
            absMaxTemp: '14.7',
            absMaxTemp_F: '58.5',
            avgDailyRainfall: '1.74',
          },
          {
            index: '4',
            name: 'April',
            avgMinTemp: '6.3',
            avgMinTemp_F: '43.3',
            absMaxTemp: '18.7',
            absMaxTemp_F: '65.7',
            avgDailyRainfall: '1.92',
          },
          {
            index: '5',
            name: 'May',
            avgMinTemp: '9.9',
            avgMinTemp_F: '49.8',
            absMaxTemp: '21.1',
            absMaxTemp_F: '70.0',
            avgDailyRainfall: '2.11',
          },
          {
            index: '6',
            name: 'June',
            avgMinTemp: '12.7',
            avgMinTemp_F: '54.9',
            absMaxTemp: '22.7',
            absMaxTemp_F: '72.9',
            avgDailyRainfall: '2.41',
          },
          {
            index: '7',
            name: 'July',
            avgMinTemp: '14.5',
            avgMinTemp_F: '58.1',
            absMaxTemp: '26.1',
            absMaxTemp_F: '79.0',
            avgDailyRainfall: '2.43',
          },
          {
            index: '8',
            name: 'August',
            avgMinTemp: '14.0',
            avgMinTemp_F: '57.2',
            absMaxTemp: '24.6',
            absMaxTemp_F: '76.3',
            avgDailyRainfall: '2.26',
          },
          {
            index: '9',
            name: 'September',
            avgMinTemp: '11.6',
            avgMinTemp_F: '52.9',
            absMaxTemp: '22.9',
            absMaxTemp_F: '73.2',
            avgDailyRainfall: '1.41',
          },
          {
            index: '10',
            name: 'October',
            avgMinTemp: '9.6',
            avgMinTemp_F: '49.3',
            absMaxTemp: '17.5',
            absMaxTemp_F: '63.5',
            avgDailyRainfall: '1.82',
          },
          {
            index: '11',
            name: 'November',
            avgMinTemp: '6.1',
            avgMinTemp_F: '43.0',
            absMaxTemp: '12.8',
            absMaxTemp_F: '55.0',
            avgDailyRainfall: '2.31',
          },
          {
            index: '12',
            name: 'December',
            avgMinTemp: '3.7',
            avgMinTemp_F: '38.7',
            absMaxTemp: '12.1',
            absMaxTemp_F: '53.8',
            avgDailyRainfall: '2.68',
          },
        ],
      },
    ],
  },
};
